services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - ./grafana:/var/lib/grafana
  
  prometheus:
    image: prom/prometheus
    ports:
      - "3002:9090"
    volumes:
      - ./prometheus:/etc/prometheus